[package]
name = "bevy_rand"
version = "0.1.0"
edition = "2021"
authors = ["Gonçalo Rica Pais da Silva <bluefinger@gmail.com>"]
description = "A plugin to integrate rand for ECS optimised RNG for the Bevy game engine."
repository = "https://github.com/Bluefinger/bevy_rand"
license = "MIT OR Apache-2.0"
keywords = ["game", "bevy", "rand", "rng"]
categories = ["game-engines", "algorithms"]
exclude = ["/.*"]
resolver = "2"
rust-version = "1.67.0"

[features]
default = ["serialize", "thread_local_entropy"]
thread_local_entropy = ["dep:rand_chacha"]
serialize = ["dep:serde", "rand_core/serde1", "rand_chacha?/serde1"]

[dependencies]
# bevy
bevy = { version = "0.10", default-features = false }

# others
serde = { version = "1.0", features = ["derive"], optional = true }
rand_core = { version = "0.6", features = ["std"] }
rand_chacha = { version = "0.3", optional = true }

[dev-dependencies]
rand = "0.8"
rand_chacha = "0.3"
ron = { version = "0.8.0", features = ["integer128"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[[example]]
name = "turn_based_game"
path = "examples/turn_based_game.rs"
